### ISSUE TITLE
Rotina TAFA421

### ISSUE THREAD

**Issue by isasimone** [andrewsegas/UTCTOOL#1]
Boa tarde!

Rotina TAFA421 abre, porém após clicar em "INCLUIR" e escolher a filial, não ocorre nenhuma ação. O mesmo ocorre para "ALTERAR" e "VISUALIZAR". Verifiquei e trata-se de rotina MVC.

Obrigada!

Isa (TAF eSocial)

**Comment by andrewsegas** [comment]
@isasimone a Rotina TAFA421 não esta em MVC, sendo assim não ira funcionar.
